### ISSUE TITLE
use of NoiseBlock and depthwise? 

### ISSUE THREAD

**Issue by listener17** [hubertsiuzdak/snac#7]
Hi! 

Interesting work. But I don't understand the following changes: 
* I think you're doing "depthwise" for reducing the number the parameters. Correct?
* What's the use of NoiseBlock in the decoder?

**Comment by hubertsiuzdak** [comment]
Hello!

- Depthwise convolutions not only reduced the parameter count, but also helped me optimize the model. After replacing most of the convolutions with DW, I could use higher learning rates without the model collapsing. Surprisingly, the perceived quality was higher!

- Injecting noise into the decoder improved my models. I believe it's helpful to introduce some stochasticity
