### ISSUE TITLE
why codebook_size=4096?

### ISSUE THREAD

**Issue by listener17** [hubertsiuzdak/snac#8]
I'm wondering why SNAC uses codebook_size=4096
(https://github.com/hubertsiuzdak/snac/blob/5e5ebadd1dc1273648464ad2ce9020be95041e12/snac/snac.py#L22)

Doesn't it mean bitrates are higher than DAC which used codebook size of 1024?
(https://github.com/descriptinc/descript-audio-codec/blob/c7cfc5d2647e26471dc394f95846a0830e7bec34/dac/model/dac.py#L156)

**Comment by lucala** [comment]
bitrate is calculated as `log2(codebook_size) * number_of_codebooks * frame_rate` 
The number of bits needed to store the codebook size grows very slowly, so even if DAC has 4x smaller codebook size, number of codebooks and frame rate are what really determine the bitrate in the end.
