### ISSUE TITLE
reconstructing audio from tokens :)

### ISSUE THREAD

**Issue by christophschuhmann** [hubertsiuzdak/snac#9]
Hi Hubert,

I already posted this on Discord, but you seem on vacation and since i am super excited, I just post it here as well. :)

![image](https://github.com/hubertsiuzdak/snac/assets/22318853/0476d832-1293-4f5b-a6c8-8afcefc39042)

**Comment by christophschuhmann** [comment]
TL;DR:  If  I have "codes" , a list of 4 tensors for the 32k hz  model, how d i get audio_hat? :)

**Comment by hubertsiuzdak** [comment]
now supported with:

```python
audio_hat = model.decode(codes)
```
